name: Test & Build & Publish
on:
  push:
    branches: [ main ]
    tags: ['[0-9]+.[0-9]+.[0-9]+']
  pull_request:
    branches: [ main ]

jobs:
  build_and_maybe_publish:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    -
      name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('./pocketbase/docker-compose.yml') }}
    - 
      name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
    - 
      uses: actions/checkout@v4
    - 
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        registry-url: "https://registry.npmjs.org"
    - 
      name: Run Pocketbase & Inbucket
      working-directory: pocketbase
      run: |
        docker compose up -d
    - 
      name: Test
      working-directory: app
      run: | 
        npm ci
        npx playwright install --with-deps
        npx playwright test
    -
      name: Playwright Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: app/playwright-report/
        retention-days: 30
    -
      # https://github.com/docker/setup-buildx-action
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      # https://github.com/docker/login-action
      name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - 
      # https://github.com/docker/build-push-action
      name: Build & Push
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        # uncomment for multi platform builds:
        # platforms: linux/amd64,linux/arm64,linux/arm/v7
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.ref_name }}
    -
      name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
    